// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhyixbMsmi_wCKlN1-QliN_q5yB2pyosw',
    appId: '1:1049308902567:web:858a8f2220faaf17fad782',
    messagingSenderId: '1049308902567',
    projectId: 'interneelearningapp',
    authDomain: 'interneelearningapp.firebaseapp.com',
    storageBucket: 'interneelearningapp.firebasestorage.app',
    measurementId: 'G-C7VB2VBTJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR8bcg1rM6o7nHh4jAwtsa6uNvelwH5Wk',
    appId: '1:1049308902567:android:ca7ee130560fa0b1fad782',
    messagingSenderId: '1049308902567',
    projectId: 'interneelearningapp',
    storageBucket: 'interneelearningapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHBC_I10pG4KViGiSoEbgKoeMUvUUI9uY',
    appId: '1:1049308902567:ios:d2a3a50eb74e2434fad782',
    messagingSenderId: '1049308902567',
    projectId: 'interneelearningapp',
    storageBucket: 'interneelearningapp.firebasestorage.app',
    iosBundleId: 'com.example.interneeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHBC_I10pG4KViGiSoEbgKoeMUvUUI9uY',
    appId: '1:1049308902567:ios:d2a3a50eb74e2434fad782',
    messagingSenderId: '1049308902567',
    projectId: 'interneelearningapp',
    storageBucket: 'interneelearningapp.firebasestorage.app',
    iosBundleId: 'com.example.interneeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhyixbMsmi_wCKlN1-QliN_q5yB2pyosw',
    appId: '1:1049308902567:web:e439ac68f6b203ccfad782',
    messagingSenderId: '1049308902567',
    projectId: 'interneelearningapp',
    authDomain: 'interneelearningapp.firebaseapp.com',
    storageBucket: 'interneelearningapp.firebasestorage.app',
    measurementId: 'G-5ZX3FP07B2',
  );
}
